[package]
name = "miniscript"
version = "4.0.3"
authors = ["Andrew Poelstra <apoelstra@wpsoftware.net>, Sanket Kanjalkar <sanket1729@gmail.com>"]
repository = "https://github.com/apoelstra/miniscript"
description = "Miniscript: a subset of Bitcoin Script designed for analysis"
license = "CC0-1.0"

[features]
fuzztarget = ["bitcoin/fuzztarget"]
compiler = []
trace = []
unstable = []
default = []
use-serde = ["bitcoin/use-serde", "serde"]
rand = ["bitcoin/rand"]

[dependencies]
bitcoin = "0.25"
elements = {git = "https://github.com/sanket1729/rust-elements", branch = "segwit_sighash"}

[dependencies.serde]
version = "1.0"
optional = true

[[example]]
name = "htlc"
required-features = ["compiler"]

[[example]]
name = "parse"

[[example]]
name = "sign_multisig"

# FIXME: Add later
# [[example]]
# name = "verify_tx"

[[example]]
name = "xpub_descriptors"
